Update apollo-server-express and lodash
globality-corp/nodule-graphql pull request #127
Opened 2021-01-21 15:07 UTC by german-glob

Updated apollo-server-express and lodash to the newest versions

2021-01-21 15:36 UTC, german-glob commented on .circleci/config.yml
> +    - image: circleci/node:10.23.1
Bumped node, because one of the dependencies of `apollo-server-express` - `lru-cache 6.0.0` is incompatible with node 8.

2021-01-22 12:08 UTC, thill-glo requested changes

2021-01-22 12:08 UTC, thill-glo commented on .circleci/config.yml
> +    - image: circleci/node:10.23.1
This breaks the spooky hash dependency. Please see: https://globalityinc.slack.com/archives/C0Q4GRU4T/p1610736515014200 and https://globalityinc.slack.com/archives/CP680HJ9E/p1611049553001700

2021-01-22 12:12 UTC, thill-glo approved these changes

2021-01-22 12:12 UTC, thill-glo commented
Sorry @german-glob didn't spot you were already waiting on @simpleigh-globality's PR. All good!

2021-01-22 14:46 UTC, simpleigh-globality commented
> Sorry @german-glob didn't spot you were already waiting on @simpleigh-globality's PR. All good!

Yep, sorry. I had a play with this last night but ran into some frustrating issues where `process.versions.napi` reports a different number than the value of `NAPI_VERSION` in the header files that `node-gyp` uses to compile the extension. I got the library running on an older version of Node but need to make the unit tests conditional on the version...

2021-01-25 13:08 UTC, simpleigh-globality commented
Replaced by #128

2021-01-25 13:08 UTC, closed without merging