Added overfetching guard to resolver class
globality-corp/nodule-graphql pull request #175
Opened 2024-03-16 10:41 UTC by german-glob

## Why?

Usually, to avoid N+1 problem, we use batching configurations, however there are cases, where number of items we fetch is too big even when batching is enabled.

See this example query:
```
query projects {
    projects {
        id
        name
        proposals {
            id
            versions {
               id
            }
        }
    }
}
```

In reality, we most likely don't need to fetch all proposal versions at the same time when we fetch projects. Instead we should  take advantage of app navigation and break this down into e.g.:
```
query projects {
    projects {
        id
        name
    }
}
```

```
query projects($projectId: ID!) {
    projects(projectId: $projectId) {
        id
        name
        proposals {
            id
        }
    }
}
```

```
query projects($projectId: ID!, $proposalID: ID!) {
    projects(projectId: $projectId) {
        id
        name
        proposals(proposalID: $proposalID) {
            id
            versions {
               id
            }
        }
    }
}
```

Right now, we don't have any way to enforce breaking such queries. This PR aims to add a configurable mechanism to resolvers, which will lead to raising an error when a resolver is subject to N+1 problem.

## What?

-  resolver can be configured using optional `maxCallsPerRequest` integer, which limits the number of times the resolver can be called within a single request.

2024-03-16 10:46 UTC, german-glob commented on src/resolvers/types.js
> +                );
FE dev usually have enough context to break down queries in initial implementation of a feature. However, we noticed that subsequent changes might easily lead to overfetching.
This error should be addressed during client implementation. We're going to introduce an alert in all envs to rule out possibility of sliping this into production.

2024-03-18 11:43 UTC, wparsons-heins-globality commented on src/resolvers/types.js
> + *  -  A `maxCallsPerRequest` integer, which limits the number of times the resolver can be called
if we're adding to this could you make this actual JSDoc?

2024-03-19 14:12 UTC, german-glob commented on src/resolvers/types.js
> +                );
I've changed it into a warning log, so it's not abused.

Apollo does provide a lot more insights, but we can alert based on logs.

2024-03-19 14:12 UTC, german-glob commented on src/resolvers/types.js
> + *  -  A `maxCallsPerRequest` integer, which limits the number of times the resolver can be called
added

2024-03-19 14:31 UTC, JP-Globality approved these changes

2024-03-19 15:07 UTC, wparsons-heins-globality requested changes

2024-03-19 15:07 UTC, wparsons-heins-globality commented on src/resolvers/types.js
>  /**
This needs to be just above the constructor not the class.

Also an extra if you want to, the functions can be typed as `() => any` for sync and `() => Promise<any>` for async to make it clearer, but it doesn't matter much.

2024-03-19 15:58 UTC, wparsons-heins-globality approved these changes

2024-03-19 16:03 UTC, merged